[".zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto.git"
[".zprezto/modules/autosuggestions/external"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
[".zprezto/modules/history-substring-search/external"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
[".zprezto/modules/syntax-highlighting/external"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
[".zsh-hist"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-hist.git"
