tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'mstrzele/napi'
brew 'libyaml'
brew 'openssl'
brew 'ansible'
brew 'autoconf'
brew 'awscli'
brew 'readline'
brew 'bash'
brew 'xz'
brew 'gmp'
brew 'coreutils'
brew 'pcre'
brew 'gettext'
brew 'git'
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
brew 'pkg-config'
brew 'x264'
brew 'lame'
brew 'libvo-aacenc'
brew 'xvid'
brew 'ffmpeg', args: ['with-flaac']
brew 'findutils', args: ['with-default-names']
brew 'gawk'
brew 'gdbm'
brew 'gnu-indent', args: ['with-default-names']
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'libtasn1'
brew 'nettle'
brew 'gnutls'
brew 'htop-osx'
brew 'hub'
brew 'libevent'
brew 'libressl'
brew 'node'
brew 'p7zip'
brew 'sqlite'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'ssh-copy-id'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'homebrew/dupes/grep', args: ['with-default-names']
brew 'homebrew/dupes/openssh', args: ['with-libressl']
brew 'homebrew/dupes/unzip'
brew 'mstrzele/napi/napi'
cask '1password'
cask 'alfred'
cask 'chefdk'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'gog-galaxy'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'plex-media-server'
cask 'skype'
cask 'spotify'
cask 'sublime-text'
cask 'utorrent'
cask 'vagrant'
cask 'viber'
cask 'virtualbox'
cask 'vlc'
