tap "go-swagger/go-swagger"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "kyoh86/tap"
brew "ansible"
brew "asciinema"
brew "aws-shell"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "brew-cask-completion"
brew "cmake"
brew "coreutils"
brew "ctop"
brew "curl"
brew "go"
brew "dep"
brew "docker-completion"
brew "findutils", args: ["with-default-names"]
brew "git"
brew "git-flow-avh"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar"
brew "graphviz"
brew "grep", args: ["with-default-names"]
brew "grip"
brew "grpc"
brew "htop"
brew "httpie"
brew "hub"
brew "jq"
brew "kubernetes-cli"
brew "kops"
brew "kubectx"
brew "kubernetes-helm"
brew "launchctl-completion"
brew "make", args: ["with-default-names"]
brew "mas"
brew "mysql"
brew "node"
brew "p7zip"
brew "pip-completion"
brew "pyenv"
brew "pyenv-virtualenv"
brew "shellcheck"
brew "ssh-copy-id"
brew "stern"
brew "terraform"
brew "tmux"
brew "vim"
brew "watch"
brew "wget"
brew "zsh"
brew "go-swagger/go-swagger/go-swagger"
brew "golangci/tap/golangci-lint"
brew "kyoh86/tap/richgo"
cask "1password"
cask "1password-cli"
cask "adobe-acrobat-reader"
cask "docker"
cask "dotnet"
cask "dropbox"
cask "forklift"
cask "gog-galaxy"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "grammarly"
cask "iterm2"
cask "microsoft-office"
cask "minikube"
cask "origin"
cask "postman"
cask "powershell"
cask "skype"
cask "spotify"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
cask "zoomus-outlook-plugin"
mas "Airmail 3", id: 918858936
mas "Evernote", id: 406056744
mas "Fantastical 2", id: 975937182
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Things3", id: 904280696
