#!/usr/bin/env zsh

[ -f "$HOME/.zshenv.local" ] && source "$HOME/.zshenv.local"

fpath=(
  "$HOMEBREW_PREFIX/share/zsh/site-functions"
  "$HOMEBREW_PREFIX/share/zsh-completions"
  $fpath
)

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
  
autoload -Uz compinit
compinit
eval "$(gh completion -s zsh)"
eval "$(op completion zsh)"; compdef _op op
source <(kubectl completion zsh)
source <(kind completion zsh)
source <(helm completion zsh)
source <(kustomize completion zsh)
eval "$(stern --completion zsh)"
source <(argocd completion zsh)

autoload bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform
eval "$(terraform-docs completion zsh)"; compdef _terraform-docs terraform-docs
source "$HOMEBREW_PREFIX/etc/bash_completion.d/az"

source "$HOME/.iterm2_shell_integration.zsh"
export ITERM2_SQUELCH_MARK=1

export SPACESHIP_CHAR_SUFFIX=' '
export SPACESHIP_CHAR_SYMBOL='$'
export SPACESHIP_KUBECTL_SHOW=true
export SPACESHIP_KUBECTL_VERSION_SHOW=false
export SPACESHIP_BATTERY_SHOW=false
export SPACESHIP_VI_MODE_SHOW=true
source "$HOMEBREW_PREFIX/opt/spaceship/spaceship.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source "$HOME/.zsh-hist/zsh-hist.plugin.zsh"
HISTSIZE=$(( 1.2 * SAVEHIST ))
bindkey "^Z" undo # ^ (control) + Z
bindkey "^[undo" undo # ⌘ (command) + Z

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
eval "$(pyenv init --path)"
path=("$PYENV_ROOT/bin" $path)
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init - $SHELL)"

function copy-command-output() {
  COMMAND="$*"
  OUTPUT_FILE="$(mktemp)"
  /bin/sh -c "$COMMAND" 2>&1 > $OUTPUT_FILE
  echo "$ $COMMAND\n$(cat $OUTPUT && rm -f $OUTPUT_FILE)" | head | pbcopy
}

alias b='brew'
alias bu='b upgrade --formulae && b cu --cleanup -y'
alias c='code'
alias cat='bat -p'
alias cd=' cd'
alias cdtemp="cd $TMPDIR"
alias crontab='CRONTAB=true crontab'
alias he=' hist e'
alias hd=' hist d'
alias hf=' hist f -1'
alias hl=' hist l'
alias fzf="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"
alias g='git'
alias go='richgo'
alias h='helm'
alias k='kubectl'
alias kctx='kubectx'
alias kns='kubens'
alias o='open'
alias s='stern'
alias tf='terraform'
alias tg='terragrunt'
alias v='vim'

kubectx kind-kind
kubectl config set-context --current --namespace=default

[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"

# vi:et:sw=2 ts=2 ft=zsh