#!/bin/sh

# Azure
source $HOMEBREW_PREFIX/etc/bash_completion.d/az

# Python
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# 1Password
eval "$(op signin)"

# Terraform
complete -o nospace -C /opt/homebrew/bin/terraform terraform
