#!/bin/sh

dimgname() { echo "$1" | sed 's#.*/\(.*\):.*#\1#'; }
drun() { docker run -it --rm "$1"; }

krun() {
  image=$1
  name=$(dimgname "$image")

  kubectl run -it --rm --image="$image" "$name"
}

otp() {
  name=$1
  vault="${2:=$OP_VAULT_NAME}"

  eval "$(op signin)"
  otp="$(op item get "$name" --vault "$vault" --otp)"
  echo $otp
}
