SPACESHIP_PROMPT_ASYNC=false

SPACESHIP_DIR_TRUNC_REPO=true

SPACESHIP_CHAR_SUFFIX=' '
SPACESHIP_CHAR_SYMBOL='$'

SPACESHIP_VI_MODE_SHOW=true

SPACESHIP_DOCKER_SHOW=false

SPACESHIP_KUBECTL_SHOW=true
SPACESHIP_KUBECTL_VERSION_SHOW=false
SPACESHIP_KUBECTL_CONTEXT_COLOR_GROUPS=(
  red   '\(kube-system)$'
  green '^localhost$'

  red    '^prod'
  yellow '^dev'
)
