#!/usr/bin/env zsh
unsetopt GLOBAL_RCS

# zprezto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# compinit
autoload -Uz compinit bashcompinit
compinit
bashcompinit

# zsh-hist
source "$HOME/.zsh-hist/zsh-hist.plugin.zsh"
bindkey "^Z" undo      # Ctrl + Z
bindkey "^[[1;3A" undo # Alt + ↑
# hist: warning: $HISTSIZE should be at least 20% larger than $SAVEHIST
export HISTSIZE=$((1.2 * SAVEHIST))

# Starship
eval "$(starship init zsh)"

# fzf
source "$HOME/.fzf.zsh"

# direnv
eval "$(direnv hook zsh)"

# iTerm2
source "$HOME/.iterm2_shell_integration.zsh"

# 1Password
eval "$(op completion zsh)"
compdef _op op

# GitHub
eval "$(gh completion -s zsh)"
compdef _gh gh

# GitLab
eval "$(glab completion -s zsh)"
# ! does NOT work in Bash
# bash: compdef: command not found
eval "$(gitlab-ci-local --completion)"

# Terraform
eval "$(terraform-docs completion zsh)"
compdef _terraform-docs terraform-docs

# Kubernetes
source <(kind completion zsh)
source <(clusterctl completion zsh)
source <(kubectl completion zsh)
source <(kustomize completion zsh)
source <(helm completion zsh)
source <(argocd completion zsh)
source <(flux completion zsh)

source <(stern --completion=zsh)

# Google Cloud Platform
source $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
source $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

source "$HOME/.completion"
source "$HOME/.aliases"
source "$HOME/.functions"
