#!/bin/sh

export LANG=pl_PL.UTF-8 LC_CTYPE=pl_PL.UTF-8 LC_MESSAGES=en_US.UTF-8
export TZ=Europe/Warsaw

export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin"
export EDITOR=vim VISUAL='codium -w'
export PAGER='bat -p' MANPAGER='col -bx | bat -l man -p'

# Homebrew
export HOMEBREW_PREFIX=/opt/homebrew
export HOMEBREW_CELLAR=$HOMEBREW_PREFIX/Cellar
export HOMEBREW_REPOSITORY=$HOMEBREW_PREFIX
export HOMEBREW_NO_ENV_HINTS=true

export PATH=$PATH:$HOMEBREW_PREFIX/opt/coreutils/bin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/gnu-getopt/bin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/openssl/bin

# prefer GNU binaries
export PATH=$PATH:$HOMEBREW_PREFIX/opt/findutils/libexec/gnubin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/gnu-indent/libexec/gnubin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/grep/libexec/gnubin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/libtool/libexec/gnubin
export PATH=$PATH:$HOMEBREW_PREFIX/opt/make/libexec/gnubin

export PATH=$PATH:$HOMEBREW_PREFIX/bin
export PATH=$PATH:$HOMEBREW_PREFIX/sbin
export PATH=$PATH:/usr/bin:/usr/sbin:/bin:/sbin

export MANPATH=/usr/local/share/man
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/coreutils/share/man
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/gnu-getopt/share/man
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/openssl/share/man

# prefer GNU manual pages
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/findutils/libexec/gnuman
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/gnu-indent/libexec/gnuman
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnuman
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnuman
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/grep/libexec/gnuman
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/libtool/libexec/gnuman
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/opt/make/libexec/gnuman
export MANPATH=$MANPATH:$HOMEBREW_PREFIX/share/man

export MANPATH=$MANPATH:/usr/share/man

export INFOPATH=$HOMEBREW_PREFIX/share/info

# less
export LESS=-R LESSHISTFILE=/dev/null

# OpenSSL
export LDFLAGS=-L$HOMEBREW_PREFIX/opt/openssl/lib
export CPPFLAGS=-I$HOMEBREW_PREFIX/opt/openssl/include
export PKG_CONFIG_PATH=$HOMEBREW_PREFIX/opt/openssl/lib/pkgconfig

# bat
export BAT_PAGER='less -RF'

# iTerm2
export ITERM2_SQUELCH_MARK=1

# Spaceship
# ! do NOT move this in ~/.spaceshiprc.zsh
# can be overwritten in .envrcs
export SPACESHIP_AWS_SHOW=false
export SPACESHIP_GCLOUD_SHOW=false

# 1Password CLI
export OP_BIOMETRIC_UNLOCK_ENABLED=true
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

# Python
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# Go
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH="$GOBIN:$PATH"

# .NET
export DOTNET_ROOT=$HOMEBREW_PREFIX/opt/dotnet/libexec

# krew
export PATH="$HOME/.krew/bin:$PATH"

# Kubeval
# https://github.com/instrumenta/kubernetes-json-schema/issues/32#issuecomment-872538205
export KUBEVAL_SCHEMA_LOCATION=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master

# AWS
export AWS_PROFILE=mstrzele
export AWS_PAGER='bat -l yaml -p'
