#!/usr/bin/env zsh

# bat
export BAT_THEME='Nord' BAT_PAGER='less -RF'
export MANPAGER="sh -c 'col -b | bat -l man -p'"

# iTerm2
export ITERM2_SQUELCH_MARK=1
source "$HOME/.iterm2_shell_integration.zsh"

# spaceship prompt
export SPACESHIP_CHAR_SUFFIX=' '
export SPACESHIP_CHAR_SYMBOL='$'
export SPACESHIP_DOCKER_SHOW=false
export SPACESHIP_KUBECTL_SHOW=true
export SPACESHIP_KUBECTL_VERSION_SHOW=false
export SPACESHIP_BATTERY_SHOW=false
export SPACESHIP_VI_MODE_SHOW=true

source "$HOMEBREW_PREFIX/opt/spaceship/spaceship.zsh"

# zprezto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  
# compinit
autoload -Uz compinit && compinit
autoload bashcompinit && bashcompinit

# zsh-hist
source "$HOME/.zsh-hist/zsh-hist.plugin.zsh"
HISTSIZE=$(( 1.2 * SAVEHIST ))
bindkey "^Z" undo # ^ (control) + Z

# fzf
source "$HOME/.fzf.zsh"

# 1Password
eval "$(op completion zsh)"; compdef _op op
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

# GitHub CLI
eval "$(gh completion -s zsh)"; compdef _gh gh

# Terraform
complete -o nospace -C /opt/homebrew/bin/terraform terraform
eval "$(terraform-docs completion zsh)"; compdef _terraform-docs terraform-docs

# Azure CLI
source "$HOMEBREW_PREFIX/etc/bash_completion.d/az"

# Kubernetes
source <(kind completion zsh)
source <(kubectl completion zsh)
source <(kustomize completion zsh)
source <(stern --completion=zsh)
source <(helm completion zsh)
source <(argocd completion zsh)

otp() {
  item_name=$1
  vault=$2

  eval "$(op signin)"
  otp="$(op item get "$item_name" --vault "$vault" --otp)"
  echo -n "$otp" | pbcopy # copy OTP to the clipboard
  echo "$otp"
}

alias b='brew'
alias bu='b upgrade --formulae && b cu --cleanup -y'
alias c='cat'
alias cdt='cd $TMPDIR'
alias d=' hist d'
alias e=' hist e'
alias g='git'
alias h='helm'
alias k='kubectl'
alias kctx='kubectx'
alias kns='kubens'
alias l=' hist l'
alias la='exa -la'
alias o='open'
alias s='stern'
alias tf='terraform'
alias tg='terragrunt'
alias v='vim'

kubectx kind-kind
kubectl config set-context --current --namespace=default

if [[ -f "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi

# vi:et:sw=2 ts=2 ft=zsh
