set-option -g default-terminal "screen-256color"
set-option -g mouse on
set-option -g set-titles on
set-option -g set-titles-string "#W"
set-option -g status-justify centre
set-option -g status-utf8 on
if-shell "test -f ~/.tmuxline.conf" "source ~/.tmuxline.conf"
